### ISSUE TITLE
clj -A:dev does not raise up prompt

### ISSUE THREAD

**Issue by stardiviner** [paulbutcher/electron-template#2]
```
myapp clojure -A:dev
2019-12-07 20:08:59.995:INFO::main: Logging initialized @23659ms to org.eclipse.jetty.util.log.StdErrLog
[Figwheel] Compiling build dev to "bin/main.js"
[Figwheel] Successfully compiled build dev to "bin/main.js" in 8.808 seconds.
[Figwheel] Outputting main file: bin/renderer.js
[Figwheel] Outputting main file: bin/tests.js
[Figwheel] Watching paths: ("src/config/dev" "src/main" "src/renderer" "src/test") to compile build - dev
[Figwheel] Starting Server at http://localhost:9500
[Figwheel] Starting REPL
Prompt will show when REPL connects to evaluation environment (i.e. Node)
Figwheel Main Controls:
          (figwheel.main/stop-builds id ...)  ;; stops Figwheel autobuilder for ids
          (figwheel.main/start-builds id ...) ;; starts autobuilder focused on ids
          (figwheel.main/reset)               ;; stops, cleans, reloads config, and starts autobuilder
          (figwheel.main/build-once id ...)   ;; builds source one time
          (figwheel.main/clean id ...)        ;; deletes compiled cljs target files
          (figwheel.main/status)              ;; displays current state of system
Figwheel REPL Controls:
          (figwheel.repl/conns)               ;; displays the current connections
          (figwheel.repl/focus session-name)  ;; choose which session name to focus on
In the cljs.user ns, controls can be called without ns ie. (conns) instead of (figwheel.repl/conns)
    Docs: (doc function-name-here)
    Exit: :cljs/quit
 Results: Stored in vars *1, *2, *3, *e holds last exception object
[Rebel readline] Type :repl/help for online help info
Launching Javascript environment with script:  ["npm" "start"]
Environment output being logged to: cljs-temp/js-environment.log
```

And the `cljs-temp/js-environment.log`:
```
/home/stardiviner/myapp/node_modules/electron/index.js:14
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
    ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at getElectronPath (/home/stardiviner/myapp/node_modules/electron/index.js:14:11)
    at Object.<anonymous> (/home/stardiviner/myapp/node_modules/electron/index.js:18:18)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/stardiviner/myapp/node_modules/electron/cli.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myapp@0.1.0 start: `electron .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the myapp@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/stardiviner/.npm/_logs/2019-12-07T12_09_46_011Z-debug.log
```

And `/home/stardiviner/.npm/_logs/2019-12-07T12_09_46_011Z-debug.log`

```
10 silly lifecycle myapp@0.1.0~start: Args: [ '-c', 'electron .' ]
11 silly lifecycle myapp@0.1.0~start: Returned: code: 1  signal: null
12 info lifecycle myapp@0.1.0~start: Failed to exec start script
13 verbose stack Error: myapp@0.1.0 start: `electron .`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/stardiviner/.nvm/versions/node/v11.14.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:193:13)
13 verbose stack     at ChildProcess.<anonymous> (/home/stardiviner/.nvm/versions/node/v11.14.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:193:13)
13 verbose stack     at maybeClose (internal/child_process.js:999:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
14 verbose pkgid myapp@0.1.0
15 verbose cwd /home/stardiviner/myapp
16 verbose Linux 5.4.2-arch1-1
17 verbose argv "/home/stardiviner/.nvm/versions/node/v11.14.0/bin/node" "/home/stardiviner/.nvm/versions/node/v11.14.0/bin/npm" "start"
18 verbose node v11.14.0
19 verbose npm  v6.7.0
20 error code ELIFECYCLE
21 error errno 1
22 error myapp@0.1.0 start: `electron .`
22 error Exit status 1
23 error Failed at the myapp@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by paulbutcher** [comment]
Have you tried doing what the error message suggests and deleting and reinstalling Electron?

**Comment by stardiviner** [comment]
I did have an Electron installed which is installed in Arch Linux through AUR. Let me have a try.

**Comment by stardiviner** [comment]
I removed system Electron, and delete `node_modules/electron`. Then execute command `npm install again`. It gets stucked on installing.
```
$ npm install

> electron@7.1.3 postinstall /home/stardiviner/myapp/node_modules/electron
> node install.js
```
From yesterday night to now. Still not finished. I checked out process status with `htop`. It barely has no activities just change the CPU usage to 0.6 sometimes.

**Comment by stardiviner** [comment]
The problem solved. Sorry about disturb.
